### ISSUE TITLE
Initial value of SystemCoreClock incorrect

### ISSUE THREAD

**Issue by fivdi** [STMicroelectronics/cmsis_device_c0#1]
`SystemCoreClock` is currently defined in system_stm32c0xx.c [like this](https://github.com/STMicroelectronics/cmsis_device_c0/blob/v1.1.0/Source/Templates/system_stm32c0xx.c#L110):

```c
  uint32_t SystemCoreClock = 48000000UL;
```

The variable `SystemCoreClock` holds the system core clock, which is the system clock frequency supplied to the processor core clock (see [here](https://arm-software.github.io/CMSIS_5/Core/html/group__system__init__gr.html#gae0c36a9591fe6e9c45ecb21a794f0f0f).)

On the STM32C0, HSISYS is used as system clock source after startup from reset, with a division factor of four. This results in a system clock frequency of 12 MHz being supplied to the processor core clock.

In my opinion, the current definition of `SystemCoreClock` is incorrect and it should be defined as like this:

```c
  uint32_t SystemCoreClock = 12000000UL;
```

**Comment by TOUNSTM** [comment]
ST Internal Reference:  162796

**Comment by TOUNSTM** [comment]
Fixed in https://github.com/STMicroelectronics/cmsis_device_c0/commit/69479b8eaf42001c5ef32c93919155a56698604e
